Algoritmo "Calcular média da nota"
// Descrição   : Calcula a média entre três valores
// Autor(a)    : Gabriel Henrique
// Data atual  : 16/02/2024
Var

   n1, n2, n3, media: real

Inicio

   escreva("Digite a primeira nota: ")
   leia(n1)
   escreva("Digite a segunda nota: ")
   leia(n2)
   escreva("Digite a terceira nota: ")
   leia(n3)
   media <- n1 + n2 + n3 / 3
   escreval("A média do aluno na disciplina foi:", media)
   
Fimalgoritmo