Algoritmo "De_100_ate_110"
// Descrição   : Imprime os 10 primeiros números inteiros depois de 100
// Autor(a)    : Gabriel Henrique
// Data atual  : 15/03/2024
Var

   cont: inteiro

Inicio

   escreval("                  -| DE 100 ATÉ 110 TEMOS |-")
   escreval

   para cont de 101 ate 110  faca

      se (cont > 101) e (cont <= 110) entao

         escreva(" -")

      fimse

      escreva(cont)

   fimpara

Fimalgoritmo