print('    «-- Calculadora de Média  --»')
nome = str(input('\n Informe o nome do aluno -> '))
nota1 = float(input(' Informe a primeira nota -> '))
nota2 = float(input(' Informe a segunda nota -> '))
nota3 = float(input(' Informe a terceira nota -> '))
media = (nota1 + nota2 + nota3) / 3
print('\n' + '=' * 55)
print(f' A notas do aluno {nome} foram: {nota1}, {nota2}, {nota3}')
print(f' A sua média foi {media:.2f}!')
print('=' * 55)
