print('          ---| VALOR DA HORA |---')
salario = float(input('\n - Digite o valor total do salário -> R$ '))
horaDia = int(input('\n - Digite o número de horas trabalhadas por dia -> '))
horaMes = (horaDia * 30)
print('\n' + '=' * 50)
print(f' * Sálario total: R$ {salario:.2f}')
print(f' * Horas diárias: {horaDia} hora(s)')
print(f' * Valor da hora: R${salario / horaMes:.2f}')
print('=' * 50)
