services:
  # Serviço Apache + PHP
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache_php
    volumes:
      - ./:/var/www/html 
    ports:
      - "8080:80" 
    depends_on:
      - db  
    user: "1000:1000"
  
  # Serviço MySQL
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase              
    volumes:
      - /PHP:/mysql-data/var/lib/mysql 
    ports:
      - "3306:3306" 
  
  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  
    ports:
      - "8081:80" 
    depends_on:
      - db

volumes:
    mysql-data: 

