services:
  # Serviço Apache + PHP
  web:
    image: php:8.1-apache
    container_name: apache_php
    volumes:
      - ./EXERCICIO_PHP:/var/www/html 
    ports:
      - "8080:80" 
    depends_on:
      - db  
  
  # Serviço MySQL
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: mydatabase        
      MYSQL_USER: user                   
      MYSQL_PASSWORD: password          
    volumes:
      - mysql-data:/var/lib/mysql 
    ports:
      - "3306:3306" 
  
  # Serviço phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db  
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8081:80" 
    depends_on:
      - db

volumes:
  mysql-data: 

